apiVersion: batch/v1
kind: Job
metadata:
  generateName: pi-job-
spec:
  template:
    spec:
      containers:
        - name: pi
          image: registry.sensetime.com/fezho/perl:latest
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
